## Tensors: multidimensional arrays
A tensor is an array: that is, a data structure that stores a collection of numbers that are accessible individually using an index, and that can be indexed with multiple indices.

### 3.2.2 Constructing our first tensors

In [6]:
import torch

a = torch.ones(3)
a[2] = 2.0
print(a)

tensor([1., 1., 2.])


We can pass a Python list to the constructor

In [7]:
points = torch.tensor([4, 1, 5, 3, 2, 1])
points

tensor([4, 1, 5, 3, 2, 1])

It would be pratical to have the first index refer to individual 2D points rather than point coordinates. We can use 2D tensors

In [9]:
points = torch.tensor([[4, 1], [5, 3], [2, 1]])
points

tensor([[4, 1],
        [5, 3],
        [2, 1]])

Here, we pass a list of lists to the constructor. We can ask the tensor about its shape:

In [11]:
points.shape

torch.Size([3, 2])

To make keeping track of dimension concrete, imagine that we have a 3D tensor like $img\_t$, and we want to convert it to gray-scale. We looked up typical weights for the colors to derive a single brightness value:

In [12]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])

We introduced an additional batch dimension in $batch\_t$; here we pretend to have a batch of 2:

In [13]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

The unweighted means can be written as:

In [14]:
img_gray_naive = img_t.mean(-3)
batch_gray_navie = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_navie.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

## 3.6 The tensor API
The vast majority of operations on and between tensors are available in the $torch$ module and can also be called as methods of a tensor object.

In [16]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

or as a method of the $a$ tensor

In [17]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

## 3.9 Moving tensors to the GPU
Every tensor can be transferred to the GPU in order to perform massively parallel, fast computations. All operations that will be performed on the tensor will be carried out using GPU-specific routines that come with Pytorch.

A Pytorch tensor also has the notion of $device$, which is where on the computer the tensor data is stored.

In [18]:
points_gpu = torch.tensor([[4, 0], [5, 3], [2, 1]], device = 'cuda')

We could instead copy a tensor created on the CPU onto the GPU using the $to$ method:

In [19]:
points_gpu = points.to(device='cuda')

Note that the $points\_gpu$ tensor is not brought back to the GPU once the result has been computed. Here's what happened in this line:
1. The $points$ tensor is copied to the GPU
2. A new tensor is allocated on the GPU and used to store the result of multiplication
3. A handle to that GPU tensor is returned